# Básico
title: "Portfólio Jonas Okawara"
description: "Bem-vindo ao meu portfólio pessoal."
baseurl: "" # Deixe vazio para GitHub Pages
url: "https://jonasmok.github.io/JonasMok/" # Substitua 'username' pelo seu nome de usuário do GitHub

# Autor
author:
  name: "Jonas Okawara"
  email: "jonas.ok@gmail.com"

# SEO
seo:
  twitter_username: "seutwitter"
  github_username: "seugithub"
  
# Tema
theme: jekyll-theme-alembic

# Layout
paginate: 5 # Número de posts por página

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Links de Navegação
navigation:
  - title: "Sobre"
    url: /about/
  - title: "Projetos"
    url: /projects/
  - title: "Contato"
    url: /contact/

# Configurações do Tema Alembic
show_excerpts: true # Mostra um resumo dos posts
show_related_posts: true # Mostra posts relacionados no final de cada post
show_tags: true # Mostra tags associadas aos posts



# Outros
markdown: kramdown
highlighter: rouge
