# Básico
title: "Portfólio de Jonas Okawara"
description: "Bem-vindo ao meu portfólio pessoal."
baseurl: "" # Deixe vazio para GitHub Pages
url: "https://jonasmok.github.io/JonasMok/" # Substitua 'username' pelo seu nome de usuário do GitHub

# Autor
author:
  name: "Jonas Okawara"
  email: "jonas.ok@gmail.com"

# SEO
seo:
  linkedin: "https://www.linkedin.com/in/jonas-manabu-okawara"
  github_username: "JonasMok"
  
# Tema
theme: alembic # Nome correto do tema para GitHub Pages

# Layout
paginate: 5 # Número de posts por página

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configurações do Tema Alembic
show_excerpts: true # Mostra um resumo dos posts
show_related_posts: true # Mostra posts relacionados no final de cada post
show_tags: true # Mostra tags associadas aos posts

# Outros
markdown: kramdown
highlighter: rouge
